artifacts_root: artifacts

data_ingestion:
  # Root directory for data ingestion artifacts
  root_dir: artifacts/data_ingestion

  # Path to the raw data file for data ingestion
  raw_data_path: artifacts/data_ingestion/raw_data.csv



data_validation:
  # Root directory for data validation artifacts
  root_dir: artifacts/data_validation

  # Path to the raw data for validation
  raw_data_path: artifacts/data_ingestion/raw_data.csv

  # Path to store the validation status
  validation_status: artifacts/data_validation/status.txt


data_transformation:
  # Root directory for data transformation artifacts
  root_dir: artifacts/data_transformation

  # Path to the raw data file from data ingestion
  raw_data_path: artifacts/data_ingestion/raw_data.csv

  # Path to the saved preprocessor (ColumnTransformer) object
  preprocessor: artifacts/data_transformation/preprocessor.pkl

  # Path to the CSV file storing the training data after transformation
  train_data: artifacts/data_transformation/train.csv

  # Path to the CSV file storing the test data after transformation
  test_data: artifacts/data_transformation/test.csv


model_training:
  # Root directory for storing artifacts related to model training
  root_dir: artifacts/model_training

  # Path to the training data CSV file
  train_data: artifacts/data_transformation/train.csv

  # Path to the test data CSV file
  test_data: artifacts/data_transformation/test.csv

  # Path to save the best-performing model
  best_model_path: artifacts/model_training/model.pkl

